WITH AVAILABLE_CARS AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    AND (
        H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01'
    )
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND H.CAR_ID IS NULL
),

DISCOUNTED_CARS AS (
    SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE,
           IFNULL((
               SELECT MAX(D.DISCOUNT_RATE)
               FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
               WHERE D.CAR_TYPE = A.CAR_TYPE
               AND CAST(SUBSTRING_INDEX(D.DURATION_TYPE, '일', 1) AS UNSIGNED) <= 30
           ), 0) AS DISCOUNT_RATE
    FROM AVAILABLE_CARS A
)

SELECT D.CAR_ID, D.CAR_TYPE,
       FLOOR(D.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100)) AS FEE
FROM DISCOUNTED_CARS D
WHERE FLOOR(D.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
