-- 코드를 입력하세요
SELECT L.FOOD_TYPE AS FOOD_TYPE, 
        L.REST_ID AS REST_ID,
        L.REST_NAME AS REST_NAME,
        L.FAVORITES AS FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS 'FAVORITES' FROM REST_INFO GROUP BY FOOD_TYPE) AS F
INNER JOIN REST_INFO AS L ON F.FOOD_TYPE = L.FOOD_TYPE AND F.FAVORITES = L.FAVORITES
ORDER BY FOOD_TYPE DESC