WITH SIGNUP2021 AS (
    SELECT *
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)

SELECT YEAR(SALES_DATE) 'YEAR', MONTH(SALES_DATE) 'MONTH', COUNT(DISTINCT USER_ID) 'PURCHASED_USER', ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(USER_ID) FROM SIGNUP2021), 1) 'PURCHASED_RATIO'
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM SIGNUP2021)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH