WITH JULY_TOTAL as (
    SELECT FLAVOR, SUM(TOTAL_ORDER) 'TOTAL_ORDER'
    FROM JULY
    GROUP BY FLAVOR
)

SELECT F.FLAVOR
FROM FIRST_HALF AS F
JOIN JULY_TOTAL AS J
ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.TOTAL_ORDER) DESC
LIMIT 3