-- 코드를 입력하세요
SELECT S.TITLE, S.BOARD_ID, E.REPLY_ID, E.WRITER_ID, E.CONTENTS, DATE_FORMAT(E.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS S
INNER JOIN USED_GOODS_REPLY AS E ON S.BOARD_ID = E.BOARD_ID
WHERE DATE_FORMAT(S.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY CREATED_DATE, TITLE