-- 코드를 입력하세요
SELECT F.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS F
INNER JOIN BOOK_SALES AS L ON F.BOOK_ID = L.BOOK_ID
WHERE SALES_DATE LIKE CONCAT('2022-01%')
GROUP BY CATEGORY
ORDER BY CATEGORY